// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9BC1zBuITMU5UAKav3HMeHLPUJWS0438',
    appId: '1:380602564226:web:afd33cf185db52f502be9b',
    messagingSenderId: '380602564226',
    projectId: 'chat-app-43f65',
    authDomain: 'chat-app-43f65.firebaseapp.com',
    storageBucket: 'chat-app-43f65.firebasestorage.app',
    measurementId: 'G-RSJNGWCRRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_YcKuSorIPB0uH-u7TvmzgVnnPp6djDQ',
    appId: '1:380602564226:android:3a9f56d6f29825ab02be9b',
    messagingSenderId: '380602564226',
    projectId: 'chat-app-43f65',
    storageBucket: 'chat-app-43f65.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJ6V7xVKrJda_sDWcuwFIMfGTGNrTNH0',
    appId: '1:380602564226:ios:50e53a0a3088d53702be9b',
    messagingSenderId: '380602564226',
    projectId: 'chat-app-43f65',
    storageBucket: 'chat-app-43f65.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication10',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGJ6V7xVKrJda_sDWcuwFIMfGTGNrTNH0',
    appId: '1:380602564226:ios:50e53a0a3088d53702be9b',
    messagingSenderId: '380602564226',
    projectId: 'chat-app-43f65',
    storageBucket: 'chat-app-43f65.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9BC1zBuITMU5UAKav3HMeHLPUJWS0438',
    appId: '1:380602564226:web:012d8dd48494a10902be9b',
    messagingSenderId: '380602564226',
    projectId: 'chat-app-43f65',
    authDomain: 'chat-app-43f65.firebaseapp.com',
    storageBucket: 'chat-app-43f65.firebasestorage.app',
    measurementId: 'G-7LT07C7M04',
  );
}
